### ISSUE TITLE
WEB: Build Basic Main Page

### ISSUE THREAD

**Issue by zbqmal** [ArtHub-AH/arthub-web#3]
**1. Intro**
Build a basic main page with some buttons to connect to other pages

**2. Acceptance Criteria**
- [x] Categories buttons
- [x] Profile button
- [x] Search button
- [x] Home button
- [x] Recommendation buttons

**Comment by hodudoho** [comment]
What is the "recommendation" for specifically? (i.e. artists, works, categories)

**Comment by zbqmal** [comment]
@hodudoho 
I meant the components by `Recommendation` under categories on main page.
