### ISSUE TITLE
WEB: Build Basic Search Page

### ISSUE THREAD

**Issue by zbqmal** [ArtHub-AH/arthub-web#4]
**1. Intro**
Build a basic search page with some buttons to connect to other pages

**2. Acceptance Criteria**
- [x] Artist buttons
- [x] Profile button
- [x] Message button

**Comment by hodudoho** [comment]
If there are going to be multiple pages, should include page number options at bottom

**Comment by zbqmal** [comment]
@hodudoho 
That's a good point. We should discuss about that. We have two options:
1. Like your opinion, we can limit the number of artist cards and add pagination thing
2. Or, we can try unlimiting the number and loading indefinitely like Facebook.
